gcash/bchd

chaincfg/params.go, peer/peer.go, wire/protocol.go
=> 2 update network params

blockchain/difficulty.go, blockchain/timesorter.go, blockchain/timesorter_test.go, blockchain/validate.go
=> Implement November 2017 hardfork

rpcclient/rawtransactions.go
- this is useful when we want to process a transaction that has been previously signed by another party without requiring the private key;
- this can be used nicely on a node configured with txindex=1, so there's no need to import the other party wallet.
=> Adding a method to send a pre-serialized raw transaction

integration/rpctest/node.go, rpcclient/net.go
Just looked at the most recent go report card and fixed a few miner issues.
- Fixed misspelled words.
- Fixed a couple golint errors around unnecessary return logic.
=> [Chore] A couple fixes for Go Report Card

Gopkg.lock
Updates cashaddr calculation to use the prefix string found in chaincfg.Params
=> Update bchutil dependency

peer/peer.go
This change address #41 and makes a TrickleInterval of 0 send all inventory as soon as it's known. Regular ticker interval usage is still supported.
This PR does not disable trickling by default. I'll leave that work and decision making to another changeset.
=> Allow completely disabling inventory trickling

addrmgr/addrmanager.go, peer/example_test.go, peer/peer.go, peer/peer_test.go, server.go
Backport from Dave Collins. Major peer refactoring. Also closes #55
=> Backport: Peer refactoring

README.md
=> Add Security Disclosure information to README.md

bchec/example_test.go, blockchain/chainio.go, blockchain/common_test.go, blockchain/compress.go, blockchain/fullblocktests/generate.go, blockchain/indexers/manager.go, blockchain/validate.go, connmgr/dynamicbanscore_test.go, database/ffldb/interface_test.go, integration/rpctest/rpc_harness_test.go, mempool/estimatefee.go, txscript/sign_test.go
Went through and cleaned up all the ineffassign mistakes in the code.
=> [Chore] Clean up all ineffassigns

btcjson/chainsvrresults.go, rpcadapters.go, rpcserver.go, rpcserverhelp.go
Just thought it would be useful. Original PR was from https://github.com/btcsuite/btcd/pull/1043
=> [Feature] Add whitelisted to getpeerinfo

blockchain/fullblocktests/generate.go, blockchain/utxoviewpoint.go
=> [Chore] blockchain: Fix a few typos

netsync/manager.go
Pulled from https://github.com/btcsuite/btcd/pull/1174
Thanks @stevenroose
=> [Fix] netsync: remove unecessary buffered channel

server.go
Just a port of https://github.com/btcsuite/btcd/pull/1283
=> [Fix] Add lock when updating knownAddresses

peer/mruinvmap.go
https://github.com/btcsuite/btcd/pull/1306
=> [Fix] Don't panic if wire.InvVect casting fails

btcjson/chainsvrwscmds.go, btcjson/chainsvrwsntfns.go, rpcclient/notify.go
Just updates all deprecation comments so they work in godoc.
https://github.com/btcsuite/btcd/pull/1291
=> [Chore] Update Deprecated comment format

wire/common_test.go
Simple test fix pulled from https://github.com/btcsuite/btcd/pull/1288
=> [Fix] Fix comparison in ReadVarBytes test case

btcjson/chainsvrresults.go, rpcclient/wallet.go
Make sure AddMultisigAddress unmarshals to the right type.
https://github.com/btcsuite/btcd/pull/1324
=> [Fix] Fix AddMultisigAddress callback unmarshalling

chaincfg/params.go
=> Bump simnet DAAForkHeight to 2000

Gopkg.lock
Updated to latest dependencies.
=> [Chore] Update dependencies to latest versions

rpcclient/chain.go, rpcclient/extensions.go
For the RPC commands `getmempoolinfo` and `getuptime` support for querying these via the rpcclient has been added.
=> Additions to rpcclient functions getmempoolinfo and getuptime

blockchain/error.go, blockchain/error_test.go, blockchain/fullblocktests/generate.go, blockchain/validate.go, rpcserver.go
Add a new error and split the debug log between missing and spent TxOuts
Addresses issue #157
=> Add error ErrSpentTxOut to indicate spent TxOut

Gopkg.lock, blockchain/chain.go, blockchain/process.go, rpcserver.go, rpcserverhelp.go
Sometimes a block gets marked as invalid that needs to be revalidated. This just adds the `reconsiderblock` rpc call just in case that happens.
=> [Feature] Add support for reconsiderblock

bchec/ecmh.go, bchec/ecmh_test.go
Spec here: https://github.com/tomasvdw/bips/blob/master/ecmh.mediawiki
=> Add ecmh go implementation

blockchain/difficulty.go, blockchain/process.go
My node freaked out with the errors below. After looking at the code, I realized that some old BTC santity checks were not updated for the new DAA. Upon closer investigation I don't believe these checks are actually needed at all. PoW has already been checked, and there are times that block timestamps have come out of order. Also, we reduce a lookup on the checkpoint block on each processed block so it should speed things up.
If we want to reintroduce this later, then we can fix `b.calcEasiestDifficulty` and reintroduce the logic.
```
I  2018-12-15 20:22:21.968 [INF] SYNC: Rejected block 000000000000000007d770b79a1a8df6437e30507a89f97de19850eaa50f8e12 from 35.201.194.117:8333 (outbound): block target difficulty of 0000000000000000089e95000000000000000000000000000000000000000000 is too low …
```
=> [Fix] Remove checkpoint based block sanity tests

README.md
Based on jonald's experience + my own experience + discussion in slack. The intention is to give somebody who is not already familiary the first steps on how to interact with the node / wallet.
Posting a [similar PR to bchwallet](https://github.com/gcash/bchwallet/pull/22).
=> Expand cli intro

Gopkg.lock, Gopkg.toml, blockchain/fastsync.go
Just finishes up the grab integration. Now we can support the proxy through my custom fork of Grab. Hopefully they merge it into mainline.
=> [Feature] Add socks5 support for fastsync download

bchec/bchec_test.go, bchec/bench_test.go, bchec/example_test.go, bchec/privkey_test.go, bchec/signature.go, bchec/signature_test.go, blockchain/fullblocks_test.go, blockchain/fullblocktests/generate.go, blockchain/validate.go, chaincfg/params.go, txscript/engine.go, txscript/engine_test.go, txscript/opcode.go, txscript/sigcache_test.go, txscript/sign.go
Spec here: https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/2019-05-15-upgrade.md
This branch successfully synced the May 2019 hardfork testnet to the tip using the following params https://docs.google.com/document/d/1NEQ8Yjr_ckyH-z-CZPbHse0_6_CEPQv214lurQ-0aUg
=> Implement May 2019 hardfork

Gopkg.lock, Gopkg.toml, blockchain/fastsync.go
downloadUtxoSet now uses displayDownloadProgress to display the download progress of the UTXO set during synchronisation
=> Download Progress during UTXO sync

Gopkg.lock, blockchain/indexers/cfindex.go, mempool/mempool.go, server.go
See issue #205 for more discussion.
=> Update bchutil package with new filter format

blockchain/chain.go, rpcserver.go, rpcserverhelp.go
This just adds `invalidateblock` to the rpc interface.
I was able to invalidate a block, then reconsider it and everything went back to normal. I was just impatient in my testing before. =)
Please give it a test, but I think we are good to go!
=> [Feature] Add invalidateblock implementation

blockchain/chain.go
This is some minor cleanup on the invalidate/reconsider logic.
- Make sure to unset the valid flag on the invalidated block.
- Make sure to unset the valid flag and set the invalid ancestor flag on detached nodes.
Now reconsiderblock works correctly if you specify the invalidated chain tip.
=> Set flags on ancestors of invalidated blocks

Gopkg.lock, bchrpc/server.go, grpcserver.go
Enables clients to inspect the server proto implementation and check compatibility.
=> Add grpc server reflection

bchrpc/server.go
The RPC had a bug where it would only return the last 100 utxos. This commit
patches it to return all utxos for the given address.
=> Fix bug in GetAddressUnspentOutput RPC

blockchain/fullblocks_test.go, blockchain/validate.go, chaincfg/params.go
Need someone to double check these values for both mainnet and testnet
=> Params updates for hardfork

txscript/engine.go, txscript/opcode.go, txscript/script.go
Stepping backwards is still buggy in this PR.
=> Add additional debugging options in txscript package

config.go, sample-bchd.conf
I have gone through *config.go*, checked all fields of the `config` struct and added the missing ones to *sample-bchd.conf*. Wherever a default was available I used it. Values with no default I set to the value that the person uncommenting the option would likely want.
See issue #239.
=> Update sample-bchd.conf with new config options

bchrpc/documentation/nginx.md
update nginx config to make use of nginx ngx_http_grpc_module
=> update nginx grpc config

bchrpc/server.go
=> Fix gRPC bug returning unspent outputs

bchrpc/server.go, server.go
Just new errors I saw running `./goclean.sh`.
=> [Chore] Fix new round of linting errors

chaincfg/params.go
=> [Chore] Add testnet-seed.bchd.cash

bchrpc/pb-js/bchrpc_pb.d.ts, bchrpc/pb-js/bchrpc_pb.js, bchrpc/pb-js/package-lock.json, bchrpc/pb-js/regen.sh, bchrpc/pb/bchrpc.pb.go
Update protos for Go and TypeScript. Plus a package_lock.json so people can easily install the required protoc plugin for ts.
=> [Chore] Update protos and regen script for ts

peer/peer.go, wire/message.go
Backport of https://github.com/btcsuite/btcd/pull/1462
=> [Bug] Include verack as part of version handshake

bchd.go, config.go, server.go
Allows you to whitelist and blacklist peers based on user agent. Ported from https://github.com/btcsuite/btcd/pull/1418
=> [Feature] Configurable UserAgent filtering

bchec/musig.go, bchec/musig_test.go
Add musig faculties to bchec package.
=> Implement MuSig in the bchec package.

mining/mining.go
Fixes https://github.com/gcash/bchd/issues/341
There was already a test to make sure it was 100 bytes or greater. Test still passes. =)
=> [Bug] Fix coinbase transaction padding calculation

chaincfg/params.go, chaincfg/params_test.go
Removes dns seeds that no longer work. Plus adds tests to make sure the right testnet seeds are defined.
=> [Chore] Remove invalid seeds and add testnet seed test

chaincfg/params.go, chaincfg/params_test.go
They were renamed, and now we are adding them back. =)
=> [Chore] Add back bitcoinforks seeders

peer/peer.go
Should fix https://github.com/gcash/bchd/issues/349
@jtoomim it would be great if you could validate this patch works. =)
=> [Feature] Don't disconnect peer that sends unhandled command

.travis.yml, blockchain/scriptval.go, blockchain/validate.go, rpcserver.go, rpcwebsocket.go, server.go, txscript/opcode.go
Bumps golangci-lint and fixes linting errors.
=> [Chore] Fix linting errors and bump golangci-lint version for Travis

bchrpc/server.go
Noticed we had an off by 1 on the number of confirmations. Quick fix. =)
=> [Bug] Fix off by 1 error on number of confirmations for tx's in grpc API

docs/README.md, docs/cifs.md, docs/default_ports.md
Unfortunately I couldn't find a quality code fix for this issue, however I figured we should at least document it for CIFS users.
Fixes https://github.com/gcash/bchd/issues/367
=> [Chore] Update docs so CIFS users know to turn off async preemption

bchrpc/documentation/client_usage.md
Update the link in client_usage.md to bchrpc.proto so that it does not 404 anymore.
=> Update link to bchrpc.proto

blockchain/difficulty.go, chaincfg/params.go, server.go
=> Update chain params for post hardfork activation

chaincfg/params.go, chaincfg/params_test.go
Doesn't work for me anymore. Would love for someone else to confirm and then we can merge this.
=> [Chore] Remove seed-bch.bitcoinforks.org seed as it no longer works

server.go
Seeing a lot of connections to peers on a different chain. This will help clean that up somewhat.
=> Don't connect to ABC nodes

blockchain/indexers/common.go, blockchain/indexers/manager.go
Currently the slp index seems to get stuck when indexing slp during IBD.
=> Fix IBD indexing for slp index

netsync/manager.go
This cleans up the syncing code a bit.
1) `isSyncCandidate` now only covers service bits, and is not called every time we check a peer.
2) Don't include peers behind us in the median calculation. 
@jcramer take a peek =)
=> [Chore] Isolate height checks in peer syncing

bchrpc/bchrpc.proto
=> fix typo in line 63

bchrpc/proxy/gw.go
Fixes https://github.com/gcash/bchd/issues/510
=> Update Read/Write Timeout to 5 minutes for expensive lookups

btcjson/walletsvrcmds.go, rpcclient/rawtransactions.go
[JSON-RPC](https://docs.bitcoincashnode.org/doc/json-rpc/signrawtransactionwithkey/)
=> Feautre PR - add signrawtransactionwithkey JSON-RPC

wire/msgsendcmpct_test.go, wire/msgtx_test.go, wire/msgxverack_test.go
make function comment match function name
=> chore: make function comment match function name

wire/common_test.go, wire/invvect_test.go, wire/msgblocktxns_test.go, wire/msgfilterclear_test.go, wire/msgfilterload_test.go
fix some function names in comment
=> chore: fix some function names in comment

addrmgr/network.go, bchec/field.go, bchec/privkey.go, bchec/pubkey.go, blockchain/chainio.go, blockchain/fullblocktests/generate.go, btcjson/cmdparse.go, btcjson/doc.go, database/driver.go, database/ffldb/blockio.go, database/ffldb/db.go, database/ffldb/interface_test.go, database/internal/treap/immutable_test.go, mining/mining.go, peer/mruinvmap.go, peer/mrunoncemap.go, txscript/doc.go, txscript/scriptnum.go
remove duplicate word in comment
=> chore: remove duplicate word in comment

bchrpc/regtest/bchd.conf, bchrpc/regtest/lib/rpc.ts, btcjson/jsonrpc.go, config.go, doc.go, sample-bchd.conf
=> chore: fix some typos in comment

rpcserver.go, server.go, txscript/script.go, txscript/standard.go
=> chore: fix some comments
