gcash/bchd

- txscript/example_test.go
- txscript/sign_test.go
Just converts the remaining legacy addresses to cashaddr in the test suite. Ran a regexp across all test files. I think this should be all of them. =)
Fixes https://github.com/gcash/bchd/issues/14
> [Chore] Convert remaining legacy addresses in tests to cashaddr

- Dockerfile
Adds a Dockerfile which builds a basic bchd image.
- Mounts a volume at `/data`
- Points the datadir to `/data`
- Points the config file to `/data/bchd.conf` so it can easily be stored and edited.
If you want any tweaks let me know.
Also built the image which you can check out at https://hub.docker.com/r/zquestz/bchd/tags/
> [Feature] Add Dockerfile to easily setup bchd

- kube/README.md
- kube/bchd-deployment.yml
- kube/bchd-secrets.yml
- kube/bchd-srv.yml
Documentation and configurations for setting up bchd on Kubernetes.
I also have a node live with a very similar config at `bchd.greyh.at:8333`. Seems to be working quite well, although I am still syncing. =)
> [Feature] Add kubernetes configs for GCE

- .gitignore
- Dockerfile
- README.md
- kube/bchd-deployment.yml
A few changes:
1) Documentation!
2) Full support for `bchctl` with no funky args.
3) Updated kubernetes to always fetch latest image.
4) .gitignore bchd
> [Chore] Update Docker and Kubernetes Configs

- peer/peer.go
This PR attempts to address issue #41.
This reduces the inventory trickle interval from 10 seconds to 1 millisecond and increases the max size from 1000 to 5000. This makes nodes send more txs at once and reduces the time new txs have to wait before being broadcast. An interval of 0 (that doesn't use a `time.Ticker`) is not supported to prevent a continuous inv flood from starving out other outgoing data tasks in the same `select` as the inv broadcast.
> Adjust trickle size and minimum broadcast interval

- config.go
- server.go
Sets a limit of 5 incoming and outgoing connections to a particular host. This is configurable via the `maxpeersperip` flag.
Addresses https://github.com/gcash/bchd/issues/40
> [Feature] Add MaxPeersPerIP to limit too many connections from a single ip address

- blockchain/fullblocktests/generate.go
- blockchain/validate.go
- blockchain/validate_test.go
- mempool/mempool.go
- mempool/policy.go
- mining/mining.go
- rpcserver.go
- txscript/script.go
- txscript/script_test.go
- txscript/standard.go
- txscript/standard_test.go
So I believe this should fix the sigops counts pre anomaly. I am not 100% sure this is right, and I had to pass around the flag a lot. Maybe I missed something.
Hopefully this is useful, if so we can write some tests. =)
Also if anyone wants to make changes, feel free to push to this branch.
Start of fix for https://github.com/gcash/bchd/issues/47
> [Fix] Fix sigops handling pre nov upgrade

- btcjson/chainsvrresults.go
- rpcserver.go
- rpcserverhelp.go
The getpeerinfo rpc currently returns the services field as a uint whichis mostly worthless as it's not human readable. This commit changes it to return the string representation of the node's services.
I presume it was done this way so that clients can more easily parse the field, however the main client using it is bchctl and not being human readable is a drawback. Any other clients that need to parse it can still parse the string.
> Change getpeerinfo services response to a string

- blockchain/chain.go
- blockchain/fullblocktests/generate.go
- blockchain/process.go
- blockchain/validate.go
- blockchain/validate_test.go
- mempool/mempool.go
- mempool/policy.go
- mining/mining.go
- txscript/engine.go
- txscript/script.go
- txscript/script_test.go
- txscript/standard.go
- txscript/standard_test.go
This resolves the code debt introduced by passing the magneticAnomalyActive bool around instead of the current ScriptFlags set. This should be much cleaner to maintain for future hard forks.
> [Refactor] Update magneticAnomalyActive bool to ScriptFlags

- version.go
We only changed `bchctl` before. This bumps the main bchd to beta2.
> [Chore] Be consistent, bump to beta2 in bchd

- peer/peer.go
This is just a fix from https://github.com/btcsuite/btcd/pull/1144 to address stalled syncing that I was experiencing. I can confirm it is far more stable for me now.
> [Fix] Disconnect peers with malformed messages immediately

- database/error.go
- database/error_test.go
- database/ffldb/db.go
- database/ffldb/disk.go
- database/ffldb/disk_darwin.go
- database/ffldb/disk_dragonfly.go
- database/ffldb/disk_freebsd.go
- database/ffldb/disk_linux.go
- database/ffldb/disk_windows.go
Prevents writes when the disk is low on space.
Currently supports:
- darwin
- linux
- windows
- freebsd
- dragonfly
Other platforms have a stub that always allows writes. Go doesn't have a good way to calculate disk space on these platforms due to limitations in the syscall package.
Based off the work done in https://github.com/btcsuite/btcd/pull/1156
NOTE: Right now I don't think this supports mounted disks for the data dir. I will amend this to support that case in a follow up PR.
> [Feature] Prevent writes when disk space is limited

- bchec/field.go
This uses the addition chain from Brian Smith's website to speed up the inversion algorithm for btcec/field.go.
https://briansmith.org/ecc-inversion-addition-chains-01#secp256k1_field_inversion
Just porting from the PR found at https://github.com/btcsuite/btcd/pull/1087
Thank you @bmperrea for the work. =)
> [Speedup] Optimize field inversion

- database/ffldb/db.go
- database/ffldb/disk.go
- database/ffldb/disk_darwin.go
- database/ffldb/disk_dragonfly.go
- database/ffldb/disk_freebsd.go
- database/ffldb/disk_linux.go
- database/ffldb/disk_windows.go
Update the disk space checks to the location of the leveldb storage. This should now support mounted volumes for the data dir.
> [Fix] Check disk space at the level db store path

- bchec/ciphering.go
- bchec/ciphering_test.go
Thanks to @AdamISZ for the fix found at https://github.com/btcsuite/btcd/pull/1108
This just makes sure we follow RFC2315.
> [Fix] Validate PKCS7 padding correctly

- btcjson/chainsvrresults.go
There are cases where the hex field is empty and returns an empty string. Better to just not include the key if it is nil.
Pulled from https://github.com/btcsuite/btcd/pull/1131
> [Fix] Add omitempty to Hex field of TxRawResult

- netsync/manager.go
- netsync/manager_test.go
This is just a small improvement to the sync node selection. The previous selection was extremely poor, and merely grabbed the last possible candidate (the last one that connected). This caused the selection to be limited and I believe is the culprit behind the long stalls I have seen.
The new algo is simple but should improve things.
1) Look for a peer at a higher block height, then randomly select one of them.
2) If there are no peers at a higher block height, allow a connection to the same block height. This mirrors what happens today but makes this case merely a fallback.
In testing this is working well. I have not seen a stall with this patch.
> [Feature] Improve sync node selection algo

- mempool/estimatefee.go
- txscript/opcode.go
Simply avoids copying arrays when it isn't needed.
Grabbed from https://github.com/btcsuite/btcd/pull/1290
> [Fix] mempool,txscript: avoid big array copies in for-range

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- btcjson/chainsvrresults.go
- btcjson/cmdinfo_test.go
- btcjson/example_test.go
- btcjson/help.go
- btcjson/help_test.go
- rpcclient/chain.go
- rpcserver.go
- rpcserverhelp.go
https://github.com/btcsuite/btcd/pull/1232
Thansks @reinerRubin
> [Feature] Update getblock verbosity semantics

- rpcclient/wallet.go
Easily get transaction data from watchOnly addresses.
Originally written by @gertjaap in https://github.com/btcsuite/btcd/pull/1163
> [Feature] Add support for watchOnly transaction listing

- chaincfg/params.go
Neutrino is using simnet and barfing on the difficulty adjustment since you need historical blocks to calculate the difficulty and you don't have any at the beginning of the chain. Actually not sure why bchd isn't having an issue with this on simnet and regtest right now, but the easiest path is to just make the DAA activate later. 
If I figure out how to calculate the DAA early in the chain maybe I can switch it back.
> Update DAAForkHeight for Simnet params

- connmgr/connmanager.go
There is a chance that a connection was canceled while waiting to retry. Check the state before reconnecting.
https://github.com/btcsuite/btcd/pull/1330
> [Fix] On connect check canceled state

- btcjson/walletsvrcmds.go
- btcjson/walletsvrcmds_test.go
- rpcclient/wallet.go
Add easy way to send a transaction with the fee removed from the sending amount.
Ported from https://github.com/btcsuite/btcd/pull/1155
> [Feature] Add SubtractFeeFromAmount params to SendToAddressCmd

- chaincfg/params.go
- chaincfg/params_test.go
- kube/bchd-deployment.yml
Adds `seed.bchd.cash` to our default seeds and removed `seeder.criptolayer.net` which was unreliable. Also back-filled some very basic tests.
> [Chore] Add seed.bchd.cash to the seed list

- peer/peer_test.go
Unfortunately there is a race condition in the peer tests. I had a few failures on unrelated changes and figured I would reduce the race condition window. Unfortunately this doesn't completely fix the issue, but is more reliable in my testing.
Basically there is a race condition between when the snapshot is taken, and the values becoming stale. To address this, I just take the snapshot right before each comparison. Not great but I don't see a better way.
> [Fix] Improve reliablity of peer test

- netsync/manager.go
- peer/peer.go
This PR fixes the stalled syncing issue when a node stops broadcasting blocks. It does NOT fix the slow peer issue, that will be saved for a future PR.
The general idea is we have a timer that runs every 30 seconds. If no block is found in 3 minutes and we are still below the chain height then we select a new sync peer. If we are at the current block we happily stay with the sync peer we currently have.
I tested this by firewalling off the connection to my current sync peer. It then successfully switched nodes and jumped to a new peer.
Note I removed the syncPeerMutex, as I realized it is not needed. Everything goes through blockHandler which maintains synchronization. Learning more about the code every day. =)
Let me know what you think.
Thanks to @eyeamera for the thorough review. =)
> [Fix] Update sync peer when no blocks are received

- rpcserver.go
When you called `getinfo` it was reporting the wrong protocol version.
> [Bug] Fix RPC reporting of protocol version

- config.go
- netsync/interface.go
- netsync/manager.go
- server.go
Fixes: https://github.com/gcash/bchd/issues/98
This adds more logic to the sync manager so that slow sync peers are detected and disconnected.
Right now the rules are super simple, but it would be easy to adjust. We run the sync peer ticker every 30 seconds, if for 3 consecutive ticks the peer is below 50k/sec then they get disconnected.
The speed is configurable via the `minsyncpeernetworkspeed` command line flag, and the violations threshold can easily be changed via a constant in `manager.go`.
> [Feature] Add slow sync peer detection

- server.go
The RPC uptime command was returning unix time now() instead of the number of seconds the server had been running. This was due to a bug on the initialisation order of the startupTime variable occurring after the RPC server instance had been created by function newRPCServer(). Subsequently an uninitialised (zero) value was being passed to the RPC config resulting in the uptime calculation being now() - 0.
For reference the same PR was opened on upstream btcsuite source at  https://github.com/btcsuite/btcd/pull/1343
> Bug Fix: Uptime was returning unix time now instead of number of seconds up

- rpcclient/mining.go
- rpcserverhelp.go
With reference to issue https://github.com/gcash/bchd/issues/112 this PR fixes the rpcclient code to handle the float64 type.
> Fix rpcclient getnetworkhashps JSON marshall error 

- blockchain/indexers/blocklogger.go
- blockchain/indexers/manager.go
- btcjson/chainsvrresults.go
- netsync/blocklogger.go
- netsync/manager.go
- rpcadapters.go
- rpcserver.go
- rpcserverhelp.go
The RPC server command `getblockchaininfo` supports field `VerificationProgress` but the logic to calculate and output this has not yet been implemented.  This PR adds support to the RPC server to do  this including a modification to the logger to output the progress of the block sync.
Given the RPC query `bchctl getblockchaininfo` the new output includes fields `verificationprogress` and `syncheight`.
<pre><code>
{
"chain": "testnet3",
"blocks": 949495,
"headers": 949495,
"bestblockhash": "0000000000b6aa443f707fd28ad62a0d127cf14bad7e1fee177b26704ed02f38",
"difficulty": 1,
"mediantime": 1475174633,
<b>"verificationprogress": 0.7497141675010028,
"syncheight": 1266476,</b>
"pruned": false,
"softforks": [
{
"id": "bip34",
"version": 2,
"reject": {
"status": true
}
},
{
"id": "bip66", …
> Enhancement: Implemented output for block sync VerificationProgress on the RPC server and logger

- cmd/addblock/import.go
There isn't a good way to get to the ExcessiveBlockSize parameter from the main binary. For now I just set it to the default.
Fixes https://github.com/gcash/bchd/issues/116
> [Fix] Set ExcessiveBlockSize for addblock

- kube/bchd-deployment.yml
Wanted this in before the utxo cache changes land. This extends the termination grace period to 5 minutes. This should avoid nasty shutdown issues.
> [Chore] Extend docker termination grace period to 5 minutes

- blockchain/indexers/blocklogger.go
- netsync/blocklogger.go
- netsync/manager.go
Per discussion in https://github.com/gcash/bchd/issues/115 this PR fixes the following;
1. Fix the stale variable usage
2. Shorten the progress output to format of `height 1260193/1266701 (99.49%)`
3. Adjust the code to handle the data race so an up to date chain reports `height 1266701 (100.00%)`
Sample output whilst syncing
```
2018-11-07 22:50:19.384 [INF] SYNC: Processed 794 blocks in the last 10s (6045 transactions, height 141466/1233077 (11.47%), 2013-11-15 10:52:42 +0000 UTC)
2018-11-07 22:50:29.390 [INF] SYNC: Processed 1426 blocks in the last 10s (6385 transactions, height 142892/1233077 (11.59%), 2013-11-16 00:54:58 +0000 UTC)
2018-11-07 22:50:39.392 [INF] SYNC: Processed 855 blocks in the last 10s (6598 transactions, height 143747/1233077 (11.66%), 2013-11-16 20:39:05 +0000 …
```
> bug fixes to block sync progress reporting

- bchd.go
- integration/bip0009_test.go
- integration/csv_fork_test.go
- integration/rpcserver_test.go
- integration/rpctest/bchd.go
- integration/rpctest/node.go
- integration/rpctest/rpc_harness.go
- integration/rpctest/rpc_harness_test.go
Fixes #122
The root problem of #122 is basically that low test coverage allows the node to fail unexpectedly in the integration test. This PR should make it easier to find those cases until coverage is higher also keep `/tmp` clean for what that is worth.
This PR still leaves the test binary at `bchd/rpctest/bchd` but it's always the same place so /shrug.
> [FIX] Make node errors visible in integration tests and always clean up

- blockchain/fullblocks_test.go
- blockchain/process.go
- blockchain/scriptval.go
- blockchain/validate.go
- chaincfg/params.go
- config.go
- integration/rpctest/blockgen.go
- mempool/mempool.go
- mining/mining.go
- params.go
- rpcserver.go
When reviewing please make sure the values are correct. The actual fork heights used for activation of new rules are correct and that the checkpoint hashes match what your nodes are reporting.
Also, at some point we need to take a deep dive into the tests as the all fail on regtest and simnet if the forks are active from the start. Hence regtest and simnet fork heights are not set to zero.
Regtest at minimum should probably be zero but it requires big time test refactoring.
> Update magnetic anomaly fork activation

- blockchain/chain.go
- blockchain/utxocache_test.go
As I understand it, the reorg seems to have failed to un-spend some entries.
My best guess was that cached spends were not being included in the un-spend loop of the reorg function.
This is my naive attempt at a solution. Just flush the cache before reorging.
1. Not sure I got the problem right in the first place.
1. It seems there must be a more sophisticated way to include cache spends in the unmark phase, but I couldn't find a way to do it. The code is centered around the content in the block so the flush was an easy way to get the result I wanted.
If this is off-base, any feedback would be appreciated.
> make sure to unspend entries in the cache when reorging

- netsync/blocklogger.go
Saw the following in my logs:
```
I  2018-11-17 20:55:05.718 [INF] SYNC: Processed 1 block in 26m14.56s (7545 transactions, height 557081 (0.00%), 2018-11-17 20:54:18 +0000 UTC, ~61 MiB cache)
I  2018-11-17 20:28:51.155 [INF] SYNC: Processed 1 block in 12m18.28s (37 transactions, height 557080 (0.00%), 2018-11-17 20:27:59 +0000 UTC, ~57 MiB cache)
I  2018-11-17 20:16:32.869 [INF] SYNC: Processed 1 block in 7m17.83s (9 transactions, height 557079 (0.00%), 2018-11-17 20:16:05 +0000 UTC, ~57 MiB cache)
I  2018-11-17 20:09:15.028 [INF] SYNC: Processed 1 block in 2m45.08s (999 transactions, height 557078 (100.00%), 2018-11-17 20:09:09 +0000 UTC, ~57 MiB cache)
I  2018-11-17 20:06:29.940 [INF] SYNC: Processed 1 block in 29m0.76s (36 transactions, height 557077 (100.00%), 2018-11-17 20:05:51 …
```
> [Bug] Fix 0% progress logging problem

- bchd.go
- config.go
When you run `bchd -h` it was printing the help twice. This just fixes the output so it only shows once. The final error from `bchMain` doesn't need to be printed, upstream it prints what is needed.
> [Bug] Fix double printed help

- addrmgr/addrmanager.go
- addrmgr/network.go
- cmd/bchctl/config.go
Fixes possible bugs due to naming collisions with built-in types and imported package names.
> Avoid naming collisions

- config.go
- config_test.go
Just adds the EB value to the UserAgent. Uses the same format as ABC.
```
/bchd:0.13.0(EB32.0)/
```
> [Feature] Add EB to UserAgentComments

- peer/peer.go
- server.go
Currently, we don't send our own IP when receiving getAddr messages, this makes sure to include it in the address list.
Testing this now. =)
EDIT: And I have been seen!
```
"35.202.172.160:8333":{"version":"\/bchd:0.13.0\/","country":"US","height":557436,"flags":293}
```
> [Bug] Add BestLocalAddress when responding to getAddr messages

- bchd.go
- blockchain/chain.go
- blockchain/chain_test.go
- cmd/addblock/import.go
- config.go
- database/cmd/dbtool/insecureimport.go
- database/driver_test.go
- database/ffldb/whitebox_test.go
- integration/csv_fork_test.go
- integration/rpctest/rpc_harness_test.go
- netsync/common_test.go
- peer/peer_test.go
- txscript/reference_test.go
- wire/common.go
- wire/common_test.go
- wire/message.go
- wire/message_test.go
- wire/msgblock.go
- wire/msgblock_test.go
- wire/msgcfcheckpt.go
- wire/msgmerkleblock.go
- wire/msgmerkleblock_test.go
- wire/msgreject.go
- wire/msgreject_test.go
- wire/msgtx.go
- wire/msgtx_test.go
Fixes #102, #110 
This is more of a request for feedback. As described in #102, the race condition is not such a big deal - it's more of a test issue. However it showed more importantly that there are many fake static configuration values as documented in #110.
I tried 3 ways to fix it with minimal changes:
1. Threading the EBS dependency into everything that needs it. This just made the `wire` package a mess and made it harder to use as well.
1. (This PR) Initializing EBS in the wire package explicitly. This is a pain because everyone that uses it has to initialize the package. However, it turned out to be the cleanest fix that I found.
1. [Refactor a new `config` package](https://github.com/gcash/bchd/compare/master...emergent-reasons:isolate-config) so that any package can get EBS and …
> [FIX] make dependent wire limits actually dependent

- config.go
- server.go
Adds a new configuration option `targetoutboundpeers` to set the connection target for outbound peers. Many nodes will want to be above 8, including mine. =)
> [Feature] Add configuration option for targetOutboundPeers

- blockchain/chain.go
- blockchain/utxocache.go
We hit a bug with the following setup. Block 559307(a) was mined creating a new
utxo (u). An alternate block 559307(b) was mined which did not create u. Subsequently
559308 was mined on top of b which did create u again. So during the reorg u
needed to go from unspent to spent(removed) when block a was disconnected, then
back to unspent again when block 559308 was connected. However, the utxocache
commit() function did not have the ability to override a utxo previously marked
as spent back into an unspent state and thus u was left marked as spent. When
559309 was mined spending u, it failed to validate because u was erroneously marked
as spent already.
This commit patches the commit() function to allow overriding from spent to
unspent.
> Fix utxo reorg bug

- server.go
Potential panic here. Just guards the `addrCache` being empty.
> [Bug] Check length of addrCache before removing an element

- version/version.go
When fastsync is merged, we should probably bump to beta2. =)
> Bump version to 0.13.0-beta2

- blockchain/utxocache.go
Resolves https://github.com/gcash/bchd/issues/172
When restoring the utxo set from an inconsistent state, we were going back 1 block too far. This just adjusts the logic so it works correctly for fastsync.
Be great if one other person tested this. =)
> Fix InitConistentState to roll back correctly

- blockchain/utxocache.go
This fixes a couple bugs in the UTXO set reconstruction code. Specifically the
roll forward starts one block too early resulting in a UTXO missing error.
Also it was missing a break from the final rollforward loop which caused it
to remain stuck forever.
> Fix bugs in UTXO rollback

- peer/peer.go
- server.go
- wire/message.go
- wire/msgcfmempool.go
- wire/msggetcfmempool.go
Get a filter of the remote peer's mempool. Can be used by lite client to decide whether to download the mempool at startup.
> Add GetCFMempool functionality

- mempool/mempool.go
- server.go
- txscript/script.go
- wire/msggetcfmempool.go
The `GetCFMemPool` function actually had incorrect behavior. It's supposed to return the prevout script for each returned tx but it was only checking the utxo cache for prevout scripts meaning it might omit prevout scripts from mempool transactions spending from other transactions in the mempool. 
Also add a filter type to the getcfmempool request.
This PR fixes this along with some comments in the function.
> Fix OnGetCFMempool function

- peer/peer.go
- server.go
- wire/message.go
- wire/msgxverack.go
- wire/msgxverack_test.go
- wire/msgxversion.go
- wire/msgxversion_test.go
This adds a basic stub for xversion messages so we don't disconnect BU clients as reported in https://github.com/gcash/bchd/issues/184
This implements:
- Support for xversion and xverack message types.
- Replies to xversion messages with an xverack.
- Makes sure the xversion message is below the size limit.
- Makes sure only one xversion is received per client.
This does not actually implement the xversion message parsing or pull any data from the xversion.
Can confirm connections to BU nodes with these changes.
```
{
"104.199.108.13:8333" => "/Bitcoin ABC:0.18.3(EB32.0)/",
"47.91.95.148:8333" => "/Bitcoin ABC:0.18.3(EB32.0)/",
"73.243.165.156:8333" => "/BUCash:1.5.1(EB32; AD12)/",
"198.204.229.34:8333" => "/Bitcoin ABC:0.19.0(EB32.0)/",
"74.72.248.101:8333" => "/bchd:0.14.0(EB32.0)/", …
```
> [Feature] Add stub for xversion messages

- blockchain/indexers/addrindex.go
- blockchain/indexers/cfindex.go
- blockchain/indexers/common.go
- blockchain/indexers/manager.go
- blockchain/indexers/txindex.go
This commit creates a Migrate method in the indexer interface. It also adds
a migration to the cfilter index which just drops the index and rebuilds. The
purpose it make sure all nodes are using the same index as the filtering code
has changed recently and it appears some nodes have a different index.
> Create indexer migrations

- txscript/opcode.go
bchd choked on transaction [b0f79eea9e05fe83e198efff4363e3e347d5efd77a22fbf39a09347162fb2560](https://www.blockchain.com/bch/tx/b0f79eea9e05fe83e198efff4363e3e347d5efd77a22fbf39a09347162fb2560).
It contained an extremely long script sig with hundreds of opcodes. When tracing the stack execution it was determined that OP_CAT was mutating items deeper in the stack. This commit fixes the bug. 
Nodes will need to run 
```
bchctl reconsiderblock 0000000000000000001df2299a0d705bc95df7045398a32d1dea5ccff7bb9fb6
```
to fix their chain.
Thanks to Mark Lundeberg for pinpointing the bug.
> Fix bug in OP_CAT

- rpcserver.go
This was not updated when we added CompactBlocks support. Now it returns `70015` as it should. =)
> [Fix] Update getinfo rpc call to return correct protocol version

- txscript/engine.go
- txscript/engine_test.go
The May hardfork spec has changed to reflect a different implementation in
the bitcoin-abc codebase. It was determined it would be easier to get bchd
nodes to upgrade with a different spec than to get all bitcoin-abc nodes
to upgrade to the existing spec.
The specific change allows the top stack item to be zero when the script is
segwit exempt.
> Update to latest May hardfork spec

- bchec/ecmh.go
`big.Int.abs` is a pointer, so if you copy the value of `big.Int` it will copy its pointer to `abs` instead of its value. If we want to copy `big.Int` properly we need to use `big.Int.Set`
> Fix NewMultisetFromPoint to copy bigint properly

- blockchain/utxocache.go
The code here wants to override the existing entry in the cache in the reorg case. However, the override bool was left to false so `addEntry` wouldn't actually do the override. 
Also, by setting `ourEntry` to `entry` rather than a _copy_ of `entry` any modifications to `entry` performed later (which happens at least when the view is pruned) will unintentionally modify the cache.
> Override utxo entry in reorg case

- bchrpc/server.go
The GetTransaction RPC tries to load input metadata for each input. If it's a
coinbase transaction there is no metadata and this was causing an error.
> Fix bug loading coinbase transacations in gRPC API

- mining/mining.go
- mining/mining_test.go
The template calculated the padding for the coinbase incorrectly and some coinbases could end up under the 100 byte minimum.
fixes #237
> Fix bug in blocktemplate generation

- grpcserver.go
Grpcserver did not catch the pre-flight OPTIONS request as CORS and served it with plain http server while it should be served by wrappedGrpc with CORS. This commit should fix that.
> Fix CORS for grpc-web

- bchec/signature.go
Node chocked while validating the schnorr signature for 41c2a2340c2aae0e22bbd2452712af5dfbb7304a249d470410d577277ff92357 input 0.
To fix node after this commit is merged:
`bchctl reconsiderblock 000000000000000000788b661a692dfbcd8043228758468fe3ce109aa1c69036`
> Fix bug in schnorr signature verification

- database/ffldb/blockio.go
When scanning block files, ignore files that don't end in `.fdb`. That way we can ignore .DS_Store files or other unneeded files without preventing startup!
Fixes: https://github.com/gcash/bchd/issues/244
> [Bug] Only scan fdb files when loading block files.

- blockchain/chain.go
This should fix issue https://github.com/gcash/bchd/issues/262
Currently we only send blocks to downstream nodes if it is accepted. Therefore, if we get blocks that are not accepted, and there is a reorg, those notifications are never sent.
This merely makes sure during a reorg to send blocks to downstream nodes after we connect them to our main chain again. That way we are guaranteed to relay all important blocks to downstream peers and prevent them from hanging.
> [Fix] Make sure downstream peers get new blocks on reorg

- bchrpc/server.go
- go.mod
Fixes https://github.com/gcash/bchd/issues/280
Since HaveTransaction returns false for transactions spent in the mempool, we needed to add an additional check. The code isn't super pretty, but it does fix the issue reported. Tested and deployed on bchd.greyh.at.
> [Bug] Check for spent status in mempool

- blockchain/indexers/manager.go
- server.go
Neutrino technically cannot sync from fasysynced nodes since the fastsync nodes are calculating the filter headers incorrectly. This is because the filter header contains the hash of the previous header but the fastsync nodes don't know the hash prior to the checkpoint. So the filter headers are incorrect for every block going forward. 
In theory we can still index and migrate pruned (but not fastsynced) nodes since they do calculate filters from genesis. This would require figuring out the height of the first block that is stored and migrating from there. This is not easy to do however.
> Don't migrate indexes if pruned

- blockchain/utxoviewpoint.go
I did some profiling work on bchd and noticed that when UtxoEntry objects are built we are passing in a pointer to a slice of bytes containing the PkScript. This caused wire.MsgTx objects to not GC until the UTXO cache was flushed. While this didn't leak, it did cause bchd to have higher memory usage than necessary. In my testing this reduces memory usage about 200MB with a 450MB UTXO cache.
If people are using larger cache sizes then this would be even worse. The simple fix is just to copy the bytes of the PkScript and that allows the GC to reclaim the original MsgTx.
> [Bug] Allow wire.MsgTx objects to be GC'd before UTXO cache is flushed

- blockchain/utxoviewpoint.go
Noticed I missed a few places. One code path only runs for reorgs which I didn't see in my initial pprof work.
This is mainly for correctness and consistency, but it does lead to a lot less memory bloat during reorgs.
> Make sure pkScript is copied for addTxOut and disconnectTransactions

- blockchain/chain.go
- blockchain/indexers/manager.go
The fast sync feature is not playing nice with the recent migration due to
the chain being pruned. If someone runs their node without the fastsync flag
after previously doing so, it will get into a bad state.
This commit sets the indexManger to nil inside the blockchain package if it
was ever run in fast sync mode previously.
closes #294
> Set indexManger to nil if chain is pruned

- .dockerignore
- Dockerfile
- Dockerfile.distroless
Multi stage build helps to reduce image size. Also, [distroless](https://github.com/GoogleContainerTools/distroless) makes image more secure.
In my environment, current docker image is 1GB, and the docker image using distroless is 88MB.
> Use multi stage build

- blockchain/accept.go
- blockchain/chain.go
Hopefully fixes the panic we saw on reorg. Should prevent a double unlock from ever occurring.
> [Bug] Add notificationLock mutex to protect against double unlock

- config.go
For people that use SSL terminated load balancers it is important to only warn if they bind to a non-localhost address. We shouldn't assume how someone has their infra setup.
> [Chore] Warn instead of exit on binding a non localhost address for rpc/gRPC

- txscript/pkscript.go
- txscript/pkscript_test.go
Just updated `ParsePkScript` to accept the chain params as a parameter. That way it can support non-mainnet networks.
I grepped through all the other projects, it doesn't seem like anyone uses it, so the function signature change shouldn't impact our other repos.
> [Feature] Update ParsePkScript to support multiple networks

- rpcclient/infrastructure.go
- rpcclient/wallet.go
Now you can configure an rpc client with the required network. If the param isn't passed in it assumes mainnet. This removes the hard coded network settings in wallet.go!
Based off the work at https://github.com/btcsuite/btcd/pull/1467/files
Fixes: https://github.com/gcash/bchd/issues/313
> [Bug] Refactor wallet.go to remove hard coded MainNetParams

- rpcwebsocket.go
Backports:
https://github.com/btcsuite/btcd/pull/1444
https://github.com/btcsuite/btcd/pull/1449
Just optimizes rescans so they don't happen if there are no addresses or utxos.
> [Feature] Skip rescan if client has no addresses or UTXOs

- server.go
Brings in the following backports for:
https://github.com/btcsuite/btcd/pull/1477
https://github.com/btcsuite/btcd/pull/1480
https://github.com/btcsuite/btcd/pull/1485
For the most part it is a port of these changes, but I had to make some modifications for our compact blocks support. Now we wait till we receive a VerAck to send the sendcmpt message!
This is actually more to spec. =)
Tested by syncing testnet, and that works perfecto. IBD on mainnet was also done.
> [Refactor] Add peers OnVerAck instead of OnVersion

- bchrpc/server.go
- txscript/engine.go
There can be a panic when a client disconnects from SubscribeTransactionStream due to a race. This checks for nil in the request.
> Check for nil req in SubscribeTransactionStream

- bchrpc/server.go
- mempool/estimatefee.go
This commit improves the memory usage of the RPC call by checking the utxos
after each batch rather than loading all transsactions into memory.
We also enforce a max query size of 10,000 on the GetAddressTransactions
and GetRawAddressTransactions RPCs.
> Improve memory usage of GetAddressUnspentOutputs RPC call

- chaincfg/params.go
- chaincfg/params_test.go
Remove long dead DNS seed seed.bitprim.org.
Remove DNS seed seed.deadalnix.me returning only itself as a node.
> Remove dead and useless DNS seeds

- go.mod
- go.sum
Updates bchutil for the autogenerated cert fix. This should allow gRPC node clients to use the auto generated cert.
Fixes: https://github.com/gcash/bchd/issues/330
> [Chore] Update bchutil for certificate generation fix

- bchec/musig.go
- bchec/musig_test.go
This commit adds a commitment round to the musig session. This is needed to prevent against attacks in the m of m case.
> Add commitments to musig session

- chaincfg/params.go
Recently my IPFS server has been getting hammered. Unfortunately it isn't just for our UTXO snapshots, but a LOT of other requests as well.
While I do want to seed the UTXO snapshots, I think its good we have a fallback just in case I disable the front facing web daemon due to abuse.
Then people can still fetch them from another location, and I can reduce the insane bandwidth ipfs is taking on my cluster.
NOTE: My underlying ipfs node will still be up serving up the pinned files!
> Add ipfs.io as another public ipfs gateway for utxo snapshots

- blockchain/accept.go
- blockchain/fullblocktests/generate.go
- blockchain/process.go
- integration/rpctest/blockgen.go
- mining/mining.go
- rpcserver.go
This PR makes a few changes:
1. Whenever we create a coinbase transaction in tests we now make sure it is at least 100 bytes and pad it if necessary.
2.  Fixed `UpdateExtraNonce` so that it also pads the input correctly. Since it mutates the coinbase transaction and doesn't actually build a new coinbase the old code didn't do the right thing. Fortunately this is only used in cpu mining. =)
3. Fix block validations so invalid blocks don't get accepted through submitBlock!
CPU mined this block to test out the new code:
```
2020-05-02 23:26:16.920 [INF] MINR: Block submitted via CPU miner accepted (hash 0000000058b317f8fb152a8e24c46988baf22cab95c432201535d521a54855c1, amount 0.78126 BCH)
```
> [Bug] Update coinbase tx padding and fix validations for submitBlock

- .travis.yml
- Dockerfile
- README.md
Just makes sure we test against 1.12.x, 1.13.x and 1.14.x, and build the release binaries using 1.14.2!
> [Chore] Use Go 1.14.2 to produce release on travis

- blockchain/scriptval.go
Went over the sigchecks code and couldn't replicate the duplicate increment that @cpacia saw in testing. I did notice a couple of places we could avoid loading the value again.
> [Chore] Avoid unneeded loading of sigcheck values

- docs/json_rpc_api.md
**ws package error**
node version : 10.19.0
package manager : npm
OS : macOS
```
(node:55432) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
ERROR:Error: connect ECONNREFUSED 127.0.0.1:8334
DISCONNECTED
```
ref : https://stackoverflow.com/questions/52165333/deprecationwarning-buffer-is-deprecated-due-to-security-and-usability-issues
> fix deprecated ws package and add no tls example

- wire/msgcfilter.go
cfilters for blocks near 32 MB can greatly exceed the previous limit.
2 MiB was chosen because it is large enough to relay outlier cfilters
seen on testnet such as 1685010 bytes for block 1326440.
This addresses #378
> Raise MaxCFilterDataSize to 2 MiB

- config.go
While I love the idea of relaying a percentage of transactions with a low fee, the rest of the network just doesn't accept them. Therefore, this PR updates defaultFreeTxRelayLimit to 0.
- This makes sure submitted transactions with too low a fee get an error
- This can still be activated manually if people want to attempt to relay low fee transactions.
Should help mitigate issues seen by read.cash in https://github.com/gcash/bchd/issues/382
> Default to disable relay of free (super low fee) transactions

- bchrpc/bchrpc.proto
- bchrpc/server.go
Add more explanatory documentation to protoc methods, types and fields.
- Makes **no change** to the protocol itself. 
- Adds specificity for terms used to refer to many things, 
- Adds synonyms for words used interchangeably 
- Aims to provides an outside audience a succinct explanation,
or enough key terms to obtain more information elsewhere.
- Note quirks and defaults, where possible.
> Add more proto documentation

- rpcserver.go
Enable support for http-keepalive's on the JSON-RPC interface. In addition we gain HTTP2 support by getting rid of the hijack code!
I have tested this extensively and it works great with curl/wget/bchctl. I also was able to mitigate the issue that required the hijack code. By setting the `ReadHeaderTimeout` it can check the RPC auth and then allow an auth'd client to use the `ReadTimeout` for long poll requests.
I also updated the code to use the built in http `CloseNotifier`. 
Fixes: https://github.com/gcash/bchd/issues/380
> [Feature] Enable http-keepalives/HTTP2 on JSON-RPC interface!

- version/version.go
Currently the version string in BCHD returns in a format different than other BCH nodes. This makes people parsing this value have a hard time, so I figured we should update it. The `version.Numeric()` function is only called in one place in any gcash code, and is exclusively used in `getnetworkinfo`.
While this is a breaking change if someone is parsing it, I think it should be fine to change without a major version bump.
Here is a sample response:
```
{
"version": 160400,
"subversion": "/bchd:0.16.4(EB32.0)/",
"protocolversion": 70015,
"localservices": "SFNodeNetwork|SFNodeBloom|SFNodeBitcoinCash|SFNodeCF",
"localrelay": true,
"timeoffset": 0,
"connections": 14,
"networkactive": true,
"networks": [
{
"name": "ipv4",
"limited": false,
"reachable": true,
"proxy": "", …
```
> [Feature] Return version in getnetworkinfo the way ABC/BCHN does

- bchec/field.go
- bchec/field_test.go
- blockchain/chainio.go
- blockchain/utxocache.go
- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- btcjson/jsonrpcerr.go
- connmgr/dynamicbanscore.go
- connmgr/dynamicbanscore_test.go
- database/internal/treap/README.md
- rpcclient/rawtransactions.go
An incomplete set of backports with minor changes.
- rpcclient: serialize nil inputs to empty list
https://github.com/btcsuite/btcd/pull/1558
- btcjson: add RPC_IN_WARMUP error code
https://github.com/btcsuite/btcd/pull/1541
- BUG:dynamicbanscore deadlock
https://github.com/btcsuite/btcd/pull/1509
- readme: remove duplicate word
https://github.com/btcsuite/btcd/pull/1569
- Improve chain state init efficiency
https://github.com/btcsuite/btcd/pull/1580
- Add blockchain.NewUtxoEntry()
https://github.com/btcsuite/btcd/pull/1588
- btcec: Avoid panic in fieldVal.SetByteSlice for large inputs
https://github.com/btcsuite/btcd/pull/1602
> [Chore] Collection of backports

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- btcjson/example_test.go
- btcjson/helpers.go
- rpcclient/chain.go
- rpcclient/rawtransactions.go
Updated the remaining Verbose/Verbosity arguments found in the RPC to handle either int or bool values. This fixes the last quirk mentioned in https://github.com/gcash/bchd/issues/385.
The updated methods were:
- getrawtransaction
- searchrawtransactions
Note: there is some important naming.
`VerbosityLevel` allows [0,1,2,true,false] to support `getblock`
`VerboseLevel` allows [0,1,true,false] to support `getrawtransaction` and `searchrawtransactions`.
Here is some sample working curl calls.
```
curl --header "Content-Type: application/json" https://127.0.0.1:8334/ -d '{ "jsonrpc": "2.0", "id":   1, "method": "getrawtransaction", "params": ["9d7cb019c6cdba505193a70e60d59b8f2145afa79065c957e05c6389630249b0"] }' -k
curl --header "Content-Type: application/json" https://127.0.0.1:8334/ -d '{ …
```
> [Feature] Update verbosity arguments to accept int or bool in getrawtransaction and searchrawtransactions

- peer/peer.go
- peer/peer_test.go
Fix from https://github.com/btcsuite/btcd/pull/1606/
> This modifies the UpdateLastBlockHeight function to ensure the new
> height is after the existing height before updating it in order to
> prevent it from going backwards so it properly matches the intent of the
> function which is to report the latest known block height for the peer.
> 
> Without this change, the value will properly start out at the latest
> known block height reported by the peer during version negotiation,
> however, it will be set to lower values when syncing from the peer due
> to requesting old blocks and blindly updating the height.
> 
> It also adds a test to ensure proper functionality.
> 
> This is a backport of decred/dcrd#1747
I think this might be the issue we see when syncing in Neutrino and the sync …
> [Bug] peer: prevent last block height going backwards

- bchrpc/bchrpc.proto
The previous protobuffer package generated for java is set to "pb", which
created a strange structuring when imported into Java.  This change moves
the generated code to com.bchd.rpc.Bchrpc.
> Added protobuffer package for Java.

- btcjson/cmdparse_test.go
- mempool/policy.go
- mempool/policy_test.go
- upnp.go
- wire/message.go
This was checking for 1MB which is the consensus rule. It should be checking the standardness rule in this function!
> [Bug] Update max standard tx size to 100k

- txscript/standard.go
ABC does not enforce this rule neither in the standard nor mandatory flags.
https://github.com/Bitcoin-ABC/bitcoin-abc/search?q=SCRIPT_VERIFY_MINIMALIF&unscoped_q=SCRIPT_VERIFY_MINIMALIF
Not sure if this requires any tests.
> Remove ScriptVerifyMinimalIf from StandardVerifyFlags

- netsync/manager.go
Had a stall on bchd.greyh.at that caused the node to fall behind. It was stuck on a sync peer that was behind other peers and somehow didn't realize it was a bad peer.
I have added logic that if a majority of sync peer candidates are ahead of us, then we should probably select a new peer!
> [Feature] Select new sync peer if median of sync peer candidates are ahead of us

- .travis.yml
- Dockerfile
Fixes security issues in multiple critical packages.
https://groups.google.com/g/golang-nuts/c/c-ssaaS7RMI/m/5iS6JRtOAwAJ?pli=1
> [Chore] Update builds to use Go 1.15.5

- chaincfg/params.go
- chaincfg/params_test.go
Remove one invalid seed now serving peers from another network. Add two new seeds to replace it on mainnet, and one for testnet.
> Fix seeds list after hard fork

- bchrpc/server.go
Fixes https://github.com/gcash/bchd/issues/414
> [Bug] Return pubkey outputs in pb.bchrpc.GetAddressUnspentOutputs

- mempool/estimatefee.go
Quick fix based on the conversation at https://github.com/btcsuite/btcd/issues/1660.
Basically the cause of the double unlock is not really a mutex issue, but a defer issue due to an out of index panic in the fee estimator. This just puts a guard on the index value. When a more robust fix is available we can use that, but with BCH we don't really need a fee estimator to be perfect. =)
> [Bug] Fix panic in fee estimator from reorgs

- config.go
Fixes https://github.com/gcash/bchd/issues/412 by making sure you can't run indexes on a pruned node.
Whoever picks up https://github.com/gcash/bchd/issues/302 can remove this small patch.
> [Bug] Print error and exit if indexing and running a pruned node

- chaincfg/params.go
In order to add the following NewSlpAddressPubKeyHash method in bchutils these params need to be added to bchd since there is a dependency on bchd/chaincfg, otherwise, `net.SlpAddressPrefix` is missing in bchutils.
```
// NewSlpAddressPubKeyHash returns a new SLP AddressPubKeyHash.
func NewSlpAddressPubKeyHash(pkHash []byte, net *chaincfg.Params) (*AddressPubKeyHash, error) {
addr, err := newAddressPubKeyHash(pkHash, net)
if err != nil {
return nil, err
}
addr.prefix = net.SlpAddressPrefix
return addr, nil
}
```
> Add slp params to chaincfg

- bchrpc/server.go
GetAddressUnspentOutputs can really hammer the server if an address is passed
in with a very large transaction history.
This adds a shutdown check every time through the loop which will terminate
the RPC call if a shutdown is requested while the RPC call is still processing.
> Check for server shutdown in gRPC GetAddressUnspentOutputs

- netsync/manager.go
When shutting down the peer manager would try to select a new sync peer when it didn't need to. This just adds a shutdown check to make sure that doesn't happen.
Before:
```
Jan 26 21:30:52 alucard bchd[416498]: 2021-01-26 21:30:52.281 [INF] SYNC: Sync manager shutting down
Jan 26 21:30:52 alucard bchd[416498]: 2021-01-26 21:30:52.281 [INF] SYNC: Updating sync peer, last block: 2021-01-26 21:30:22.941960491 -1000 HST m=+31.269384516, violations: 0
Jan 26 21:30:52 alucard bchd[416498]: 2021-01-26 21:30:52.281 [WRN] SYNC: No sync peer candidates available
Jan 26 21:30:52 alucard bchd[416498]: 2021-01-26 21:30:52.281 [INF] CHAN: Flushing UTXO cache of ~1 MiB to disk. For large sizes, this can take up to several minutes...
Jan 26 21:30:52 alucard bchd[416498]: 2021-01-26 21:30:52.285 [INF] …
```
> [Bug] Add shutdown check to updateSyncPeer

- blockchain/utxocache.go
- blockchain/utxocache_test.go
- server.go
We have bugs where a hard shutdown often leaves the utxo set in a bad state resulting in blocks being rejected on startup. The only way to fix your node if this happens is to re-run bchd with `--reindexchainstate` and use the `reconsiderblock` command. This can take upwards of 24 hours to reconstruct the utxo set. 
This PR attempts to fix bugs in the utxo set reconstruction and adds tests to simulate recovery from a hard shutdown.
> Fix utxo consistency bugs on hard shutdown

- addrmgr/addrmanager_internal_test.go
Travis CI tests were failing sometimes because of this...
Two tests running in parallel reading and writing to the same file
creates a race condition that causes one of the tests to fail sometimes.
Chose to remove t.Parallel() in lieu of changing the temp file name
of one tests since other tests don't use t.Parallel() and the tests
should stand alone from each other.
> fix race condition in addrmanager_internal_test

- bchrpc/server.go
- bchrpc/txfilter.go
- blockchain/indexers/slpindex.go
- blockchain/indexers/slpindex_test.go
The main thing here is the first commit making RemoveMempoolSlpTxs a private function and moving the call to the end of ConnectBlock.  The second commit is just minor things detected by go-staticcheck,
> Minor nits and slpindex cleanup

- bchec/musig.go
- bchec/musig_test.go
This adds another exported function in the `bchec` package to create an aggregate signature. This would be useful for transaction signing if we ever add cross input signature aggregation.
> Add SignMuSig function to bchec package

- peer/peer.go
Makes it easier to debug what is hanging the peer manager. Trace is super loud, so made a few logs debug messages.
> [Chore] Promote some peer logging messages from trace -> debug

- bchrpc/server.go
- blockchain/indexers/addrindex.go
- blockchain/indexers/cfindex.go
- blockchain/indexers/slpindex.go
- blockchain/indexers/txindex.go
Just adds checks to make sure a bucket is returned in our indexers. That way if we have an issue with a nil bucket, it will throw an error and not panic! The buckets should always be present, so returning an error is correct.
Mitigates https://github.com/gcash/bchd/issues/472
> [Chore] Guard against nil buckets to prevent panics

- txscript/standard.go
Other implementations consider OP_1NEGATE a "push operation", and therefore is allowed after OP_RETURN when determining transaction standardness.
We also identified that the OP_RETURN "maxDataCarrierSize" calculation is inconsistent with other implementations.  Other implementations, and the BCH Multiple OpReturn Specification consider the max size to be the total size of the locking script, which includes opcodes (and is easier to calculate).  This PR does not resolve that issue.
> FIX: OP_RETURN OP_1NEGATE is now considered a standard transaction.

- bchrpc/proxy/README.md
- bchrpc/proxy/gw.go
- bchrpc/proxy/gw_test.go
This PR:
- adds HTTPs support to the gRPC proxy. Currently all proxies run HTTPS using nginx and/or CloudFlare only. The default cert is `$HOME/.bchd/rpc.cert` (same as gRPC cert when running BCHD)
- renamed the `port` param to `http-addr` to be consistent with other HTTP params and allow binding to `address:port`
> added HTTPs support to gRPC proxy

- txscript/engine.go
Set the defaultScriptNum when cloning the script engine. This is used by meep.
> Fix bug cloning engine stacks

- server.go
This is a port of https://github.com/decred/dcrd/commit/f5fdd95eb578a485b414331836f9731fcd0f2756 to bchd.
This modifies the various aspects that deal with making nodes discoverable and making outbound connections to disable them when running in regression network test mode in the same way it is done for the simulation network test mode.
> server: Actively prevent regnet network discovery

- mempool/policy.go
- mempool/policy_test.go
- txscript/script.go
Other implementations of BCHD's txscript.IsUnspendable do not check for invalid op codes within the locking script.  Furthermore, invalid opcodes can technically become spendable in future hard forks, which could cause UTXO set corruption/incompatibility during a future upgrade if these opcodes were enabled and an already-synced node did not rebuild its UTXO set.
We discovered this discrepancy because this rule is also used when generating UTXO commitments, which makes BCHD's commitments otherwise incompatible with the (admittedly nebulous) utxo commitment specification.
> Resolved consensus incompatibility regarding txscript.IsUnspendable

- blockchain/abla_ewma_elastic_buffer.go
- config.go
- mining/policy.go
- peer/peer.go
Use the built-in max/min from the standard library in Go 1.21 to simplify the code.  https://pkg.go.dev/builtin@go1.21.0#max
> refactor: use the built-in max/min to simplify the code

- bchec/bchec_test.go
Optimize code using a more modern writing style. Official support by Go Team. https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize.
> refactor: replace []byte(fmt.Sprintf) with fmt.Appendf
